[[constraint]]
  name = "github.com/Comcast/codex"
  revision = "v0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/Comcast/webpa-common"

[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "v0.9.2"

[prune]
  go-tests = true
  unused-packages = true
